# This file may be used to create an environment using:
# $ conda create --name <env> --file <this file>
# platform: linux-64
# created-by: conda 25.3.1
_libgcc_mutex=0.1=main
_openmp_mutex=5.1=1_gnu
absl-py=2.3.0=pypi_0
accelerate=1.7.0=pypi_0
aiohappyeyeballs=2.6.1=pypi_0
aiohttp=3.12.2=pypi_0
aiosignal=1.3.2=pypi_0
annotated-types=0.7.0=pypi_0
anyio=4.9.0=pypi_0
argon2-cffi=23.1.0=pypi_0
argon2-cffi-bindings=21.2.0=pypi_0
arrow=1.3.0=pypi_0
asttokens=3.0.0=pypi_0
async-lru=2.0.5=pypi_0
attrs=25.3.0=pypi_0
babel=2.17.0=pypi_0
beautifulsoup4=4.13.4=pypi_0
bitsandbytes=0.46.0=pypi_0
blas=1.0=mkl
bleach=6.2.0=pypi_0
bump2version=1.0.1=pypi_0
bzip2=1.0.8=h5eee18b_6
ca-certificates=2025.2.25=h06a4308_0
cachetools=6.0.0=pypi_0
certifi=2025.4.26=pypi_0
cffi=1.17.1=pypi_0
charset-normalizer=3.4.2=pypi_0
comm=0.2.2=pypi_0
contourpy=1.3.2=pypi_0
cuda-cudart=12.1.105=0
cuda-cupti=12.1.105=0
cuda-libraries=12.1.0=0
cuda-nvrtc=12.1.105=0
cuda-nvtx=12.1.105=0
cuda-opencl=12.4.127=0
cuda-runtime=12.1.0=0
cudatoolkit=11.7.0=hd8887f6_10
cut-cross-entropy=25.1.1=pypi_0
cycler=0.12.1=pypi_0
datasets=3.6.0=pypi_0
debugpy=1.8.14=pypi_0
decorator=5.2.1=pypi_0
defusedxml=0.7.1=pypi_0
diffusers=0.33.1=pypi_0
dill=0.3.8=pypi_0
docstring-parser=0.16=pypi_0
executing=2.2.0=pypi_0
fastcore=1.8.2=pypi_0
fastjsonschema=2.21.1=pypi_0
fastprogress=1.0.3=pypi_0
filelock=3.17.0=py311h06a4308_0
fonttools=4.58.1=pypi_0
fqdn=1.5.1=pypi_0
freezegun=1.5.2=pypi_0
frozenlist=1.6.0=pypi_0
fsspec=2025.3.0=pypi_0
gmp=6.3.0=h6a678d5_0
gmpy2=2.2.1=py311h5eee18b_0
grpcio=1.71.0=pypi_0
h11=0.16.0=pypi_0
hf-transfer=0.1.9=pypi_0
hf-xet=1.1.2=pypi_0
httpcore=1.0.9=pypi_0
httpx=0.28.1=pypi_0
huggingface-hub=0.32.2=pypi_0
hypersloth=0.1.0=pypi_0
idna=3.10=pypi_0
importlib-metadata=8.7.0=pypi_0
intel-openmp=2025.0.0=h06a4308_1171
ipdb=0.13.13=pypi_0
ipykernel=6.29.5=pypi_0
ipython=9.2.0=pypi_0
ipython-pygments-lexers=1.1.1=pypi_0
ipywidgets=8.1.7=pypi_0
isoduration=20.11.0=pypi_0
jedi=0.19.2=pypi_0
jinja2=3.1.6=py311h06a4308_0
joblib=1.5.1=pypi_0
json-repair=0.40.0=pypi_0
json5=0.12.0=pypi_0
jsonpointer=3.0.0=pypi_0
jsonschema=4.24.0=pypi_0
jsonschema-specifications=2025.4.1=pypi_0
jupyter-client=8.6.3=pypi_0
jupyter-core=5.8.1=pypi_0
jupyter-events=0.12.0=pypi_0
jupyter-lsp=2.2.5=pypi_0
jupyter-server=2.16.0=pypi_0
jupyter-server-terminals=0.5.3=pypi_0
jupyterlab=4.4.3=pypi_0
jupyterlab-pygments=0.3.0=pypi_0
jupyterlab-server=2.27.3=pypi_0
jupyterlab-widgets=3.0.15=pypi_0
kiwisolver=1.4.8=pypi_0
ld_impl_linux-64=2.40=h12ee557_0
libcublas=12.1.0.26=0
libcufft=11.0.2.4=0
libcufile=1.9.1.3=0
libcurand=10.3.5.147=0
libcusolver=11.4.4.55=0
libcusparse=12.0.2.55=0
libffi=3.4.4=h6a678d5_1
libgcc-ng=11.2.0=h1234567_1
libgomp=11.2.0=h1234567_1
libnpp=12.0.2.50=0
libnvjitlink=12.1.105=0
libnvjpeg=12.1.1.14=0
libstdcxx-ng=11.2.0=h1234567_1
libuuid=1.41.5=h5eee18b_0
llvm-openmp=14.0.6=h9e868ea_0
loguru=0.7.3=pypi_0
markdown=3.8=pypi_0
markdown-it-py=3.0.0=pypi_0
markupsafe=3.0.2=py311h5eee18b_0
matplotlib=3.10.3=pypi_0
matplotlib-inline=0.1.7=pypi_0
mdurl=0.1.2=pypi_0
mistune=3.1.3=pypi_0
mkl=2025.0.0=hacee8c2_941
mpc=1.3.1=h5eee18b_0
mpfr=4.2.1=h5eee18b_0
mpmath=1.3.0=py311h06a4308_0
msgspec=0.19.0=pypi_0
multidict=6.4.4=pypi_0
multiprocess=0.70.16=pypi_0
nbclient=0.10.2=pypi_0
nbconvert=7.16.6=pypi_0
nbformat=5.10.4=pypi_0
ncurses=6.4=h6a678d5_0
nest-asyncio=1.6.0=pypi_0
networkx=3.4.2=py311h06a4308_0
notebook-shim=0.2.4=pypi_0
numpy=2.2.6=pypi_0
nvidia-cublas-cu12=12.6.4.1=pypi_0
nvidia-cuda-cupti-cu12=12.6.80=pypi_0
nvidia-cuda-nvrtc-cu12=12.6.77=pypi_0
nvidia-cuda-runtime-cu12=12.6.77=pypi_0
nvidia-cudnn-cu12=9.5.1.17=pypi_0
nvidia-cufft-cu12=11.3.0.4=pypi_0
nvidia-cufile-cu12=1.11.1.6=pypi_0
nvidia-curand-cu12=10.3.7.77=pypi_0
nvidia-cusolver-cu12=11.7.1.2=pypi_0
nvidia-cusparse-cu12=12.5.4.2=pypi_0
nvidia-cusparselt-cu12=0.6.3=pypi_0
nvidia-nccl-cu12=2.26.2=pypi_0
nvidia-nvjitlink-cu12=12.6.85=pypi_0
nvidia-nvtx-cu12=12.6.77=pypi_0
openssl=3.0.16=h5eee18b_0
overrides=7.7.0=pypi_0
packaging=24.2=pypi_0
pandas=2.2.3=pypi_0
pandocfilters=1.5.1=pypi_0
parso=0.8.4=pypi_0
peft=0.15.2=pypi_0
pexpect=4.9.0=pypi_0
pillow=11.2.1=pypi_0
pip=25.1=pyhc872135_2
platformdirs=4.3.8=pypi_0
prometheus-client=0.22.0=pypi_0
prompt-toolkit=3.0.51=pypi_0
propcache=0.3.1=pypi_0
protobuf=3.20.3=pypi_0
psutil=7.0.0=pypi_0
ptyprocess=0.7.0=pypi_0
pure-eval=0.2.3=pypi_0
pyarrow=20.0.0=pypi_0
pycparser=2.22=pypi_0
pydantic=2.11.5=pypi_0
pydantic-core=2.33.2=pypi_0
pygments=2.19.1=pypi_0
pyparsing=3.2.3=pypi_0
python=3.11.11=he870216_0
python-dateutil=2.9.0.post0=pypi_0
python-json-logger=3.3.0=pypi_0
pytorch-cuda=12.1=ha16c6d3_6
pytorch-mutex=1.0=cuda
pytz=2025.2=pypi_0
pyyaml=6.0.2=py311h5eee18b_0
pyzmq=26.4.0=pypi_0
readline=8.2=h5eee18b_0
referencing=0.36.2=pypi_0
regex=2024.11.6=pypi_0
requests=2.32.3=pypi_0
rfc3339-validator=0.1.4=pypi_0
rfc3986-validator=0.1.1=pypi_0
rich=14.0.0=pypi_0
rpds-py=0.25.1=pypi_0
safetensors=0.5.3=pypi_0
scikit-learn=1.6.1=pypi_0
scipy=1.15.3=pypi_0
send2trash=1.8.3=pypi_0
sentencepiece=0.2.0=pypi_0
setuptools=78.1.1=py311h06a4308_0
shtab=1.7.2=pypi_0
six=1.17.0=pypi_0
sniffio=1.3.1=pypi_0
soupsieve=2.7=pypi_0
speedy-utils=0.1.30=pypi_0
sqlite=3.45.3=h5eee18b_0
stack-data=0.6.3=pypi_0
sympy=1.13.3=py311h06a4308_1
tabulate=0.9.0=pypi_0
tbb=2022.0.0=hdb19cb5_0
tbb-devel=2022.0.0=hdb19cb5_0
tensorboard=2.19.0=pypi_0
tensorboard-data-server=0.7.2=pypi_0
terminado=0.18.1=pypi_0
threadpoolctl=3.6.0=pypi_0
tinycss2=1.4.0=pypi_0
tk=8.6.14=h39e8969_0
tokenizers=0.21.1=pypi_0
torch=2.7.0=pypi_0
torchvision=0.22.0=pypi_0
tornado=6.5.1=pypi_0
tqdm=4.67.1=pypi_0
traitlets=5.14.3=pypi_0
transformers=4.51.3=pypi_0
triton=3.3.0=pypi_0
trl=0.15.2=pypi_0
typeguard=4.4.2=pypi_0
types-python-dateutil=2.9.0.20250516=pypi_0
typing-extensions=4.13.2=pypi_0
typing-inspection=0.4.1=pypi_0
tyro=0.9.22=pypi_0
tzdata=2025.2=pypi_0
unsloth=2025.5.8=pypi_0
unsloth-zoo=2025.5.10=pypi_0
uri-template=1.3.0=pypi_0
urllib3=2.4.0=pypi_0
wcwidth=0.2.13=pypi_0
webcolors=24.11.1=pypi_0
webencodings=0.5.1=pypi_0
websocket-client=1.8.0=pypi_0
werkzeug=3.1.3=pypi_0
wheel=0.45.1=py311h06a4308_0
widgetsnbextension=4.0.14=pypi_0
xformers=0.0.29.post3=pypi_0
xxhash=3.5.0=pypi_0
xz=5.6.4=h5eee18b_1
yaml=0.2.5=h7b6447c_0
yarl=1.20.0=pypi_0
zipp=3.22.0=pypi_0
zlib=1.2.13=h5eee18b_1
